# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Email-Send
version:      2.05
version_from: lib/Email/Send.pm
installdirs:  site
requires:
    Class::Accessor::Fast:         0.19
    Email::Address:                1.80
    Email::Simple:                 1.92
    Module::Pluggable:             2.8
    Return::Value:                 1.28
    Test::More:                    0.47

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
